# Generated by Django 4.2.6 on 2023-10-30 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgendaApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='data_nascimento',
            field=models.DateField(verbose_name='Data Nascimento'),
        ),
    ]
