# Generated by Django 4.2.6 on 2023-10-31 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgendaApp', '0002_alter_agenda_data_nascimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='estado_civil',
            field=models.CharField(choices=[('S', 'Solteiro'), ('C', 'Casado'), ('D', 'Divorciado'), ('V', 'Viúvo')], max_length=1, null=True),
        ),
    ]
