# Generated by Django 4.2.7 on 2023-11-01 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgendaApp', '0003_agenda_estado_civil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='data_nascimento',
            field=models.DateField(verbose_name='Data de aniversário'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='estado',
            field=models.CharField(choices=[('SP', 'São Paulo'), ('RJ', 'Rio de Janeiro'), ('MG', 'Minas Gerais'), ('ES', 'Espírito Santo')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='nome',
            field=models.CharField(max_length=200),
        ),
    ]
